on: 
  workflow_dispatch:
  push:
jobs:
  neofetch:
    name: Run neofetch
    runs-on: [self-hosted]
    steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 'lts/*'
    - uses: actions/checkout@master
    - run: |
        # Update package lists
        apt-get update -y
    - run: |
        # Install neofetch
        apt-get install neofetch -y
    - run: | 
        # Run neofetch
        neofetch
